//! `coulisse schema` — emit the JSON Schema for `coulisse.yaml` to
//! stdout. Mirrors what `schemars` derives from the Rust `Config` type
//! across every feature crate; the committed `coulisse.schema.json` at
//! the workspace root is generated by piping this command into the file
//! and is what `# yaml-language-server: $schema=...` references in
//! example yamls.

use schemars::schema_for;

use crate::config::Config;

/// # Errors
///
/// Returns an error if the schema cannot be serialized as JSON.
pub fn run() -> Result<(), serde_json::Error> {
    let schema = schema_for!(Config);
    let json = serde_json::to_string_pretty(&schema)?;
    println!("{json}");
    Ok(())
}
